from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq
from pydantic import BaseModel, Field
from app.core.config import settings


class SEOMetadata(BaseModel):
    """
    Data model representing the structured SEO metadata generated by the AI.
    """

    meta_title: str = Field(description="The SEO-optimized title for the document.")
    meta_description: str = Field(
        description="The SEO-optimized description or meta summary for the document."
    )
    meta_routes: list[str] = Field(
        description="A list of 3-5 suggested URL routes or slugs suitable for the document content."
    )


async def generate_seo_metadata(
    parsed_content: str, primary_keyword: str
) -> SEOMetadata:
    """Generates SEO metadata from extracted document content and primary keyword using Langchain and Groq."""

    if not settings.GROQ_API_KEY:
        raise ValueError("GROQ_API_KEY not found in environment variables.")

    llm = ChatGroq(
        model_name=settings.GROQ_MODEL,
        groq_api_key=settings.GROQ_API_KEY,
        temperature=0.45,
        max_retries=3,
        model_kwargs={"top_p": 0.9},
    )

    structured_llm = llm.with_structured_output(SEOMetadata, method="json_mode")

    prompt = PromptTemplate.from_template(
        """
        <|header_start|>system<|header_end|>: You are a senior SEO strategist and conversion copywriter.
 
        Audience: Devs, founders, product managers, and non-technical readers.
 
        Task: Analyze the given content and output structured SEO metadata that improves CTR and follows Google SEO best practices for the Blog Post.
 
        The Primary Keyword for this blog post is: "{primary_keyword}"
 
        RULES:
        1. META TITLE
            - MAX 50-60 characters — count every character including spaces. If over 60, make it shorter.
            - Create a descriptive and keyword-rich meta title that highlights the reader's value. 
            - Include the primary keyword naturally.
           
        2. META DESCRIPTION
            - MAX 150-160 characters — count every character including spaces. If over 160, make it shorter.
            - Open with a sharp, conversational sentence that mirrors the reader's search intent.
            - Use natural verbs , active voice and integrate the primary keyword naturally.
            - Match the search intent of the Blog Content and maintain a Conversational tone (not an ad, no invented claims).
 
        3. META ROUTES (5 slugs):
            - Derived from Key topics in the Blog Content.
            - Lowercase and hyphens only — no dates, years, or numbers.
            - Each slug must be a descriptive phrase, not a shortened fragment.

        4. MANDATORY CONSTRAINTS:
            - To optimize for Google SEO and ensure rich search snippets, strictly adhere to the ideal character limits: 50–60 characters for titles and 150–160 for meta descriptions. If your content exceeds these limits, you MUST rephrase and condense it until it fits strictly within the allowed range.
            - ONLY use facts explicitly mentioned in the <document> and do not include filler phrases or generic greetings. 
            - Output ONLY valid JSON with no dates, years, or external commentary and no symbols.
            - Read every field aloud before finalizing — if it sounds clipped or robotic, rewrite it.
            
        <document>
        {content}
        </document>
        """
    )

    chain = prompt | structured_llm

    try:
        result = await chain.ainvoke(
            {"content": parsed_content, "primary_keyword": primary_keyword}
        )
        return result

    except Exception as e:
        print(f"[AI Generator] Error calling LLM: {e}")
        return SEOMetadata(
            meta_title="Generation Error",
            meta_description="Failed to create SEO content because of an API issue.",
            meta_routes=["error"],
        )
